package com.dpw.specshield.controller;

import com.dpw.specshield.generator.TestSuiteGenerator;
import com.dpw.specshield.generator.TestSuiteSerializer;
import com.dpw.specshield.model.TestSuite;
import com.dpw.specshield.parser.SwaggerParser;
import com.dpw.specshield.services.TestSuiteService;
import com.fasterxml.jackson.databind.JsonNode;
import com.dpw.specshield.config.KafkaConfig;
import com.dpw.specshield.dto.TestReportResponse;
import com.dpw.specshield.model.TestExecutionRequest;
import com.dpw.specshield.model.TestSuite;
import com.dpw.specshield.repository.TestExecutionRequestRepository;
import com.dpw.specshield.services.IReportCollector;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.Map;

@Slf4j
@RestController
@RequestMapping
@RequiredArgsConstructor
public class ReportController {

    private final TestExecutionRequestRepository testExecutionRequestRepository;
    private final IReportCollector reportCollector;
    private final KafkaTemplate<String, TestExecutionRequest> kafkaTemplate;
    private final KafkaConfig kafkaConfig;
    private TestSuiteService testSuiteService;

    @GetMapping("/report/{id}")
    public ResponseEntity<TestReportResponse> getReportById(@PathVariable String id) {
        log.info("Received report request for ID: {}", id);

        try {
            TestReportResponse report = reportCollector.getReportById(id);
            return ResponseEntity.ok(report);
        } catch (RuntimeException e) {
            log.error("Report not found: {}", e.getMessage());
            return ResponseEntity.notFound().build();
        }
    }

    @PostMapping("/generate")
    public ResponseEntity<?> generateTestSuite(@RequestBody(required = false) Map<String, String> headers) throws Exception {
        String autoGeneratedId =  testSuiteService.generate(headers);
        return ResponseEntity.status(HttpStatus.ACCEPTED)
                .body(Map.of(
                        "message", "Test execution request submitted successfully",
                        "executionId", autoGeneratedId,
                        "status", "PENDING"
                ));
    }
}
