package com.dpw.specshield.controller;

import com.dpw.specshield.model.TestSuite;
import com.dpw.specshield.services.TestSuiteService;
import com.dpw.specshield.dto.TestReportResponse;
import com.dpw.specshield.services.IReportCollector;
import com.dpw.specshield.model.TestExecution;
import com.dpw.specshield.utils.JsonUtils;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@Slf4j
@RestController
@RequestMapping
@RequiredArgsConstructor
public class ReportController {

    private final IReportCollector reportCollector;
    private final TestSuiteService testSuiteService;

    @GetMapping("/report/{id}")
    public ResponseEntity<TestReportResponse> getReportById(
            @PathVariable String id,
            @RequestParam(defaultValue = "0") int page,
            @RequestParam(defaultValue = "10") int size) {
        log.info("Received report request for ID: {}, page: {}, size: {}", id, page, size);

        try {
            TestReportResponse report = reportCollector.getReportById(id, page, size);
            return ResponseEntity.ok(report);
        } catch (RuntimeException e) {
            log.error("Report not found: {}", e.getMessage());
            return ResponseEntity.notFound().build();
        }
    }

    @GetMapping("/report/{id}/testcase/{testCaseId}")
    public ResponseEntity<TestExecution> getTestCaseDetail(
            @PathVariable String id,
            @PathVariable String testCaseId) {
        log.info("Received test case detail request for report ID: {} and test case ID: {}", id, testCaseId);

        try {
            TestExecution testExecution = reportCollector.getTestCaseDetail(id, testCaseId);
            return ResponseEntity.ok(testExecution);
        } catch (RuntimeException e) {
            log.error("Test case detail not found: {}", e.getMessage());
            return ResponseEntity.notFound().build();
        }
    }

    @PostMapping("/generate")
    public ResponseEntity<?> generateTestSuite(@RequestBody(required = false) Map<String, String> headers) throws Exception {
        String autoGeneratedId =  testSuiteService.generate(headers);
        return ResponseEntity.status(HttpStatus.ACCEPTED)
                .body(Map.of(
                        "message", "Test execution request submitted successfully",
                        "executionId", autoGeneratedId,
                        "status", "PENDING"
                ));
    }

    @PostMapping("/execute")
    public ResponseEntity<?> executeTestSuite(@RequestBody String rawJson) throws Exception {
        log.info("Execute endpoint hit - starting processing");
        log.info("Received execute request with raw JSON: {}", rawJson);

        try {
            JsonNode testSuite = JsonUtils.toJsonNodeFromString(rawJson);
            log.info("Successfully parsed JSON to JsonNode: {}", testSuite);
            String autoGeneratedId = testSuiteService.execute(testSuite);
            return ResponseEntity.status(HttpStatus.ACCEPTED)
                    .body(Map.of(
                            "message", "Test execution request submitted successfully",
                            "executionId", autoGeneratedId,
                            "status", "PENDING"
                    ));
        } catch (Exception e) {
            log.error("Error processing execute request: {}", e.getMessage(), e);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(Map.of("error", "Failed to process request: " + e.getMessage()));
        }
    }
}
