package com.dpw.specshield.services;

import com.dpw.specshield.converter.SwaggerToApiModelConverter;
import com.dpw.specshield.model.ApiSpec;
import com.dpw.specshield.parser.SwaggerParser;
import com.dpw.specshield.generator.TestSuiteGenerator;
import com.dpw.specshield.model.*;
import com.fasterxml.jackson.databind.JsonNode;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class TestSuiteService {

    private final SwaggerParser swaggerParser;
    private final SwaggerToApiModelConverter swaggerToApiModelConverter;
    private final TestSuiteGenerator suiteGenerator;

    public TestSuiteService(SwaggerParser swaggerParser,
                            SwaggerToApiModelConverter swaggerToApiModelConverter,
                            TestSuiteGenerator suiteGenerator) {
        this.swaggerParser = swaggerParser;
        this.swaggerToApiModelConverter = swaggerToApiModelConverter;
        this.suiteGenerator = suiteGenerator;
    }

    /** Default generate (no headers) */
    public TestSuite generate() {
        return generate(null);
    }

    /** Generate test suite with dynamic headers */
    public TestSuite generate(Map<String, String> headers) {
        Map<String, JsonNode> rawSchemas = swaggerParser.getSchemas();
        JsonNode components = swaggerParser.getComponents();

        List<ApiSpec> apiSpecs = swaggerToApiModelConverter.convert(rawSchemas);
        return suiteGenerator.buildTestSuite(apiSpecs, components, "AutoGenerated_TestSuite", headers);
    }
}
