package com.dpw.specshield.services;

import com.dpw.specshield.config.KafkaConfig;
import com.dpw.specshield.converter.SwaggerToApiModelConverter;
import com.dpw.specshield.model.ApiSpec;
import com.dpw.specshield.parser.SwaggerParser;
import com.dpw.specshield.generator.TestSuiteGenerator;
import com.dpw.specshield.model.*;
import com.dpw.specshield.repository.TestExecutionRequestRepository;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class TestSuiteService {

    private final SwaggerParser swaggerParser;
    private final SwaggerToApiModelConverter swaggerToApiModelConverter;
    private final TestSuiteGenerator suiteGenerator;
    private final TestExecutionRequestRepository testExecutionRequestRepository;
    private final KafkaTemplate<String, TestExecutionRequest> kafkaTemplate;
    private final KafkaConfig kafkaConfig;

    /** Default generate (no headers) */
    public String generate() {
        return generate(null);
    }

    /** Generate test suite with dynamic headers */
    public String generate(Map<String, String> headers) {
        Map<String, JsonNode> rawSchemas = swaggerParser.getSchemas();
        JsonNode components = swaggerParser.getComponents();

        List<ApiSpec> apiSpecs = swaggerToApiModelConverter.convert(rawSchemas);
        TestSuite testSuite = suiteGenerator.buildTestSuite(apiSpecs, components, "AutoGenerated_TestSuite", headers);

        // Create and store test execution request
        TestExecutionRequest request = new TestExecutionRequest();
        request.setTestSuiteName(testSuite.getTestSuiteName());
        request.setOriginalId(testSuite.getId());
        request.setBaseUrl(testSuite.getBaseUrl());
        request.setTestSuite(testSuite);
        request.setCreatedAt(LocalDateTime.now());
        request.setStatus("PENDING");

        // Save to database and get auto-generated ID
        TestExecutionRequest savedRequest = testExecutionRequestRepository.save(request);
        String autoGeneratedId = savedRequest.getId();

        // Publish to Kafka
        kafkaTemplate.send(kafkaConfig.getTestExecutionTopic(), autoGeneratedId, savedRequest);
        log.info("Published test execution request to Kafka with ID: {}", autoGeneratedId);

        return autoGeneratedId;
    }
}
